# Generated by Django 5.0.14 on 2026-05-28 00:33
 
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessmentresult_id_alter_dialoguelog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chinese_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='history_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='math_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='physics_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
