# Generated by Django 6.0.5 on 2026-05-26 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holland_code', models.CharField(blank=True, help_text='如: IEC', max_length=10)),
                ('holland_scores', models.JSONField(default=dict, help_text='{R: 5, I: 8, ...}')),
                ('mbti_type', models.CharField(blank=True, help_text='如: INTJ', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('gaokao_score', models.IntegerField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('selected_subjects', models.CharField(blank=True, help_text='如: 物理+化学+地理', max_length=200)),
                ('interests', models.TextField(blank=True, help_text='兴趣关键词，逗号分隔')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.JSONField(default=list, help_text='[{major_id, name, score, rank}, ...]')),
                ('weights', models.JSONField(default=dict, help_text='TOPSIS权重配置')),
                ('version', models.IntegerField(default=0, help_text='版本号：0=初始，1,2...=对话调整后')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='assessment.userprofile')),
            ],
            options={
                'unique_together': {('user', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DialogueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('system_intent', models.CharField(blank=True, help_text='解析的意图', max_length=100)),
                ('extracted_entities', models.JSONField(default=dict, help_text='提取的实体')),
                ('weights_adjusted', models.JSONField(default=dict, help_text='调整后的权重')),
                ('new_recommendations', models.JSONField(default=list, help_text='新的推荐列表')),
                ('system_response', models.TextField(blank=True, help_text='系统回复')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='assessment.recommendationresult')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='assessment.userprofile'),
        ),
    ]
